// Code generated by behaviortree. DO NOT EDIT.
// 本文件使用原生 Go 分支与调用；业务函数请写在同包独立文件中。
package behavior

import (
	bt "github.com/1xxz188/behaviortree"
	ctxpkg "github.com/1xxz188/behaviortree/examples/shared"
	"time"
)

type btDuration = time.Duration

// 编译槽位仅用于本版本运行时；稳定身份保留在节点元数据中。
const (
	// nodeMainRoot 对应树 "main" 的节点 "root"（显示名 ""）。
	nodeMainRoot = iota
	// nodeMainGate 对应树 "main" 的节点 "gate"（显示名 ""）。
	nodeMainGate
	// nodeMainRecord 对应树 "main" 的节点 "record"（显示名 ""）。
	nodeMainRecord
	// btNodeCount 是所有节点槽位的排他上界。
	btNodeCount
)

// btNodeNoParent 表示独立树入口没有父节点。
const btNodeNoParent = -1

// 工程事件枚举：以下常量用于宿主通知当前工程的行为树。
// 宿主先更新权威业务状态，再用枚举通知需要重新评估的节点。
const (
	// EventHostStateChanged 表示"宿主状态变化"。
	// 宿主状态更新后通知；示例未配置监听节点，用于展示合法的无引用事件。
	EventHostStateChanged bt.EventID = 1
)

// GateParams 是业务函数 Gate（显示名 "等待宿主异步完成"）的强类型参数。
type GateParams struct {
}

// RecordParams 是业务函数 Record（显示名 "记录业务事件"）的强类型参数。
type RecordParams struct {
	// Message 由常量或黑板字段绑定提供。
	Message string
}

// GetMessage 按编译后槽位读取黑板字段。
func GetMessage(f *bt.Frame[*ctxpkg.Context]) string { return f.Board.String(0) }

// SetMessage 在值变化时通知依赖条件。
func SetMessage(f *bt.Frame[*ctxpkg.Context], value string) { f.Board.SetString(0, value) }

// NewProgram 创建本版本共享的不可变程序，空版本名使用内容摘要。
func NewProgram(version string) *bt.Program[*ctxpkg.Context] {
	if version == "" {
		version = "6d0cbb97dab0e7efac9c73ce3b7cdaf6"
	}
	return &bt.Program[*ctxpkg.Context]{Version: version, Roots: map[string]int{
		"main": nodeMainRoot,
	}, Nodes: []bt.Node{
		{ID: "root", TreeID: "main", Parent: btNodeNoParent, End: btNodeCount},
		{ID: "gate", TreeID: "main", Parent: nodeMainRoot, End: nodeMainRecord},
		{ID: "record", TreeID: "main", Parent: nodeMainRoot, End: btNodeCount},
	}, Fields: []bt.Field{
		{ID: "message", Name: "Message", Type: bt.StringType, Default: bt.Value{String: "completed"}, Enum: []string{}},
	}, EventEnumDescription: "宿主先更新权威业务状态，再用枚举通知需要重新评估的节点。", Events: []bt.EventDefinition{
		{ID: EventHostStateChanged, Name: "宿主状态变化", CodeName: "HostStateChanged", Description: "宿主状态更新后通知；示例未配置监听节点，用于展示合法的无引用事件。"},
	}, FieldDependencies: map[string][]int{
		"message": []int{nodeMainRecord},
	}, EventDependencies: map[bt.EventID][]int{}, Step: btStep, Abort: btAbort}
}

// btStep 通过整数槽位分派到编译后的节点函数。
func btStep(f *bt.Frame[*ctxpkg.Context], node int) bt.Status {
	switch node {
	case nodeMainRoot:
		return btNodeMainRoot(f)
	case nodeMainGate:
		return btNodeMainGate(f)
	case nodeMainRecord:
		return btNodeMainRecord(f)
	}
	return bt.Failure
}

// btAbort 仅清理当前动作；运行时负责活跃子树取消和状态失效。
func btAbort(f *bt.Frame[*ctxpkg.Context], node int) {
	switch node {
	case nodeMainGate:
		Gate(f, nodeMainGate, bt.Abort, GateParams{})
	case nodeMainRecord:
		Record(f, nodeMainRecord, bt.Abort, RecordParams{Message: f.Board.String(0)})
	}
}
