// Code generated by behaviortree/codegen; DO NOT EDIT.
// 本文件使用原生 Go 分支与调用；业务函数请写在同包独立文件中。
package behavior

import (
	bt "github.com/1xxz188/behaviortree"
	ctxpkg "github.com/1xxz188/behaviortree/examples/shared"
	"time"
)

type btDuration = time.Duration

// 编译槽位仅用于本版本运行时；稳定身份保留在节点元数据中。
const (
	// nodeMainRoot 对应树 "main" 的节点 "root"（显示名 ""）。
	nodeMainRoot = iota
	// nodeMainGate 对应树 "main" 的节点 "gate"（显示名 ""）。
	nodeMainGate
	// nodeMainRecord 对应树 "main" 的节点 "record"（显示名 ""）。
	nodeMainRecord
	// btNodeCount 是所有节点槽位的排他上界。
	btNodeCount
)

// btNodeNoParent 表示独立树入口没有父节点。
const btNodeNoParent = -1

// GateParams 是业务函数的强类型参数。
type GateParams struct {
}

// RecordParams 是业务函数的强类型参数。
type RecordParams struct {
	// Message 由常量或黑板字段绑定提供。
	Message string
}

// GetMessage 按编译后槽位读取黑板字段。
func GetMessage(f *bt.Frame[*ctxpkg.Context]) string { return f.Board.String(0) }

// SetMessage 在值变化时通知依赖条件。
func SetMessage(f *bt.Frame[*ctxpkg.Context], value string) { f.Board.SetString(0, value) }

// NewProgram 创建本版本共享的不可变程序，空版本名使用内容摘要。
func NewProgram(version string) *bt.Program[*ctxpkg.Context] {
	if version == "" {
		version = "6dc314e272c0a523777b2d765eaa6699"
	}
	return &bt.Program[*ctxpkg.Context]{Version: version, Roots: map[string]int{
		"main": nodeMainRoot,
	}, Nodes: []bt.Node{
		{ID: "root", TreeID: "main", Parent: btNodeNoParent, End: btNodeCount},
		{ID: "gate", TreeID: "main", Parent: nodeMainRoot, End: nodeMainRecord},
		{ID: "record", TreeID: "main", Parent: nodeMainRoot, End: btNodeCount},
	}, Fields: []bt.Field{
		{ID: "message", Name: "Message", Type: bt.StringType, Default: bt.Value{String: "completed"}, Enum: []string{}},
	}, Dependencies: map[string][]int{
		"field:message": []int{nodeMainRecord},
	}, Step: btStep, Abort: btAbort}
}

// btStep 通过整数槽位分派到编译后的节点函数。
func btStep(f *bt.Frame[*ctxpkg.Context], node int) bt.Status {
	switch node {
	case nodeMainRoot:
		return btNodeMainRoot(f)
	case nodeMainGate:
		return btNodeMainGate(f)
	case nodeMainRecord:
		return btNodeMainRecord(f)
	}
	return bt.Failure
}

// btAbort 仅清理当前动作；运行时负责活跃子树取消和状态失效。
func btAbort(f *bt.Frame[*ctxpkg.Context], node int) {
	switch node {
	case nodeMainGate:
		Gate(f, nodeMainGate, bt.Abort, GateParams{})
	case nodeMainRecord:
		Record(f, nodeMainRecord, bt.Abort, RecordParams{Message: f.Board.String(0)})
	}
}

// btNodeMainRoot 执行树 "main" 中的节点 "root"（显示名 ""）。
func btNodeMainRoot(f *bt.Frame[*ctxpkg.Context]) bt.Status {
	const node = nodeMainRoot
	if cached, run := f.Enter(node); !run {
		return cached
	}
	s := f.State(node)
	_ = s
	for {
		switch s.Cursor {
		case 0:
			status := btNodeMainGate(f)
			if status == bt.Running {
				return f.Exit(node, status)
			}
			if status == bt.Failure {
				s.Cursor = 0
				return f.Exit(node, status)
			}
			s.Cursor++
		case 1:
			status := btNodeMainRecord(f)
			if status == bt.Running {
				return f.Exit(node, status)
			}
			if status == bt.Failure {
				s.Cursor = 0
				return f.Exit(node, status)
			}
			s.Cursor++
		default:
			s.Cursor = 0
			return f.Exit(node, bt.Success)
		}
	}
}

// btNodeMainGate 执行树 "main" 中的节点 "gate"（显示名 ""）。
func btNodeMainGate(f *bt.Frame[*ctxpkg.Context]) bt.Status {
	const node = nodeMainGate
	if cached, run := f.Enter(node); !run {
		return cached
	}
	s := f.State(node)
	_ = s
	phase := bt.Start
	if s.Started {
		phase = bt.Resume
	}
	s.Started = true
	return f.Exit(node, Gate(f, node, phase, GateParams{}))
}

// btNodeMainRecord 执行树 "main" 中的节点 "record"（显示名 ""）。
func btNodeMainRecord(f *bt.Frame[*ctxpkg.Context]) bt.Status {
	const node = nodeMainRecord
	if cached, run := f.Enter(node); !run {
		return cached
	}
	s := f.State(node)
	_ = s
	phase := bt.Start
	if s.Started {
		phase = bt.Resume
	}
	s.Started = true
	return f.Exit(node, Record(f, node, phase, RecordParams{Message: f.Board.String(0)}))
}
