// Code generated by behaviortree/codegen; DO NOT EDIT.
// 本文件使用原生 Go 分支与调用；业务函数请写在同包独立文件中。
package behavior

import (
	bt "github.com/1xxz188/behaviortree"
	ctxpkg "github.com/1xxz188/behaviortree/examples/shared"
	"time"
)

type btDuration = time.Duration

// GateParams 是业务函数的强类型参数。
type GateParams struct {
}

// RecordParams 是业务函数的强类型参数。
type RecordParams struct {
	// Message 由常量或黑板字段绑定提供。
	Message string
}

// GetMessage 按编译后槽位读取黑板字段。
func GetMessage(f *bt.Frame[*ctxpkg.Context]) string { return f.Board.String(0) }

// SetMessage 在值变化时通知依赖条件。
func SetMessage(f *bt.Frame[*ctxpkg.Context], value string) { f.Board.SetString(0, value) }

// NewProgram 创建本版本共享的不可变程序，空版本名使用内容摘要。
func NewProgram(version string) *bt.Program[*ctxpkg.Context] {
	if version == "" {
		version = "6dc314e272c0a523777b2d765eaa6699"
	}
	return &bt.Program[*ctxpkg.Context]{Version: version, Roots: map[string]int{
		"main": 0,
	}, Nodes: []bt.Node{
		{ID: "root", TreeID: "main", Parent: -1, End: 3},
		{ID: "gate", TreeID: "main", Parent: 0, End: 2},
		{ID: "record", TreeID: "main", Parent: 0, End: 3},
	}, Fields: []bt.Field{
		{ID: "message", Name: "Message", Type: bt.StringType, Default: bt.Value{String: "completed"}, Enum: []string{}},
	}, Dependencies: map[string][]int{
		"field:message": []int{2},
	}, Step: btStep, Abort: btAbort}
}

// btStep 通过整数槽位分派到编译后的节点函数。
func btStep(f *bt.Frame[*ctxpkg.Context], node int) bt.Status {
	switch node {
	case 0:
		return btNode0(f)
	case 1:
		return btNode1(f)
	case 2:
		return btNode2(f)
	}
	return bt.Failure
}

// btAbort 仅清理当前动作；运行时负责活跃子树取消和状态失效。
func btAbort(f *bt.Frame[*ctxpkg.Context], node int) {
	switch node {
	case 1:
		Gate(f, 1, bt.Abort, GateParams{})
	case 2:
		Record(f, 2, bt.Abort, RecordParams{Message: f.Board.String(0)})
	}
}

// btNode0 执行树 "main" 中的节点 "root"。
func btNode0(f *bt.Frame[*ctxpkg.Context]) bt.Status {
	if cached, run := f.Enter(0); !run {
		return cached
	}
	s := f.State(0)
	_ = s
	for {
		switch s.Cursor {
		case 0:
			status := btNode1(f)
			if status == bt.Running {
				return f.Exit(0, status)
			}
			if status == bt.Failure {
				s.Cursor = 0
				return f.Exit(0, status)
			}
			s.Cursor++
		case 1:
			status := btNode2(f)
			if status == bt.Running {
				return f.Exit(0, status)
			}
			if status == bt.Failure {
				s.Cursor = 0
				return f.Exit(0, status)
			}
			s.Cursor++
		default:
			s.Cursor = 0
			return f.Exit(0, bt.Success)
		}
	}
}

// btNode1 执行树 "main" 中的节点 "gate"。
func btNode1(f *bt.Frame[*ctxpkg.Context]) bt.Status {
	if cached, run := f.Enter(1); !run {
		return cached
	}
	s := f.State(1)
	_ = s
	phase := bt.Start
	if s.Started {
		phase = bt.Resume
	}
	s.Started = true
	return f.Exit(1, Gate(f, 1, phase, GateParams{}))
}

// btNode2 执行树 "main" 中的节点 "record"。
func btNode2(f *bt.Frame[*ctxpkg.Context]) bt.Status {
	if cached, run := f.Enter(2); !run {
		return cached
	}
	s := f.State(2)
	_ = s
	phase := bt.Start
	if s.Started {
		phase = bt.Resume
	}
	s.Started = true
	return f.Exit(2, Record(f, 2, phase, RecordParams{Message: f.Board.String(0)}))
}
