// Code generated by behaviortree/codegen; DO NOT EDIT.
// 本文件使用原生 Go 分支与调用；业务函数请写在同包独立文件中。
package behavior

import (
	bt "github.com/1xxz188/behaviortree"
	ctxpkg "github.com/1xxz188/behaviortree/examples/shared"
)

// btNodeMainRoot 执行树 "main" 中的节点 "root"（显示名 ""）。
func btNodeMainRoot(f *bt.Frame[*ctxpkg.Context]) bt.Status {
	const node = nodeMainRoot
	if cached, run := f.Enter(node); !run {
		return cached
	}
	s := f.State(node)
	_ = s
	for {
		switch s.Cursor {
		case 0:
			status := btNodeMainGate(f)
			if status == bt.Running {
				return f.Exit(node, status)
			}
			if status == bt.Failure {
				s.Cursor = 0
				return f.Exit(node, status)
			}
			s.Cursor++
		case 1:
			status := btNodeMainRecord(f)
			if status == bt.Running {
				return f.Exit(node, status)
			}
			if status == bt.Failure {
				s.Cursor = 0
				return f.Exit(node, status)
			}
			s.Cursor++
		default:
			s.Cursor = 0
			return f.Exit(node, bt.Success)
		}
	}
}

// btNodeMainRecord 执行树 "main" 中的节点 "record"（显示名 ""）。
func btNodeMainRecord(f *bt.Frame[*ctxpkg.Context]) bt.Status {
	const node = nodeMainRecord
	if cached, run := f.Enter(node); !run {
		return cached
	}
	s := f.State(node)
	_ = s
	phase := bt.Start
	if s.Started {
		phase = bt.Resume
	}
	s.Started = true
	return f.Exit(node, Record(f, node, phase, RecordParams{Message: f.Board.String(0)}))
}

// btNodeMainGate 执行树 "main" 中的节点 "gate"（显示名 ""）。
func btNodeMainGate(f *bt.Frame[*ctxpkg.Context]) bt.Status {
	const node = nodeMainGate
	if cached, run := f.Enter(node); !run {
		return cached
	}
	s := f.State(node)
	_ = s
	phase := bt.Start
	if s.Started {
		phase = bt.Resume
	}
	s.Started = true
	return f.Exit(node, Gate(f, node, phase, GateParams{}))
}
