// Package codegen 将已校验元数据编译成原生 Go 控制流，运行时不解释 JSON。
package codegen

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"sort"
	"strconv"
	"strings"

	"github.com/1xxz188/behaviortree/model"
)

// SourceLocation 关联节点的一次展开实例和生成 Go 源码位置。
type SourceLocation struct {
	TreeID string `json:"treeId"` // 原始树 ID。
	NodeID string `json:"nodeId"` // 原始节点 ID。
	Index  int    `json:"index"`  // 本版本状态槽位；子树多次调用具有不同槽位。
	Line   int    `json:"line"`   // 生成文件中从 1 开始的行号。
}

// Result 包含单个生成文件和可持久化的调试映射。
type Result struct {
	Source    []byte           `json:"-"`         // 应写入 *.gen.go 的 Go 源码。
	SourceMap []SourceLocation `json:"sourceMap"` // 节点与源码映射。
	Version   string           `json:"version"`   // 不含画布布局的内容摘要。
}

// ValidationError 为 CLI 和 Web 保留全部可定位诊断。
type ValidationError struct{ Diagnostics []model.Diagnostic } // 生成前的全部校验错误。

// MaxExpandedNodes 限制子树复用后的总展开状态，避免很小的输入指数占用内存。
const MaxExpandedNodes = 100000

// Error 返回第一个诊断作为普通 Go 错误信息。
func (e *ValidationError) Error() string {
	return fmt.Sprintf("行为树校验失败 (%d): %s", len(e.Diagnostics), e.Diagnostics[0].Message)
}

// occurrence 是生成期间使用的一个独立节点展开实例。
type occurrence struct {
	node     model.Node // 原始节点。
	tree     string     // 定义树 ID。
	parent   int        // 父槽位。
	end      int        // 连续子树槽位终点（不含）。
	children []int      // 编译后的显式有序子槽位。
}

// generator 只存在于代码生成阶段，不进入游戏运行时。
type generator struct {
	buf     bytes.Buffer                // 生成文本。
	p       model.Project               // 规范化的工程。
	nodes   []occurrence                // 前序展开后的节点。
	roots   map[string]int              // 各独立树的入口。
	defs    map[string]model.Definition // 业务函数声明。
	fields  map[string]int              // 黑板字段槽位。
	context string                      // 生成的上下文类型表达式。
}

// Generate 生成确定性的单个 Go 文件，不读写手写业务文件。
func Generate(project model.Project) (Result, error) {
	if d := model.Validate(project); len(d) > 0 {
		return Result{}, &ValidationError{d}
	}
	if err := checkExpandedSize(project); err != nil {
		return Result{}, err
	}
	// 经 JSON 深拷贝后规范化集合，避免修改调用者的工程或画布。
	raw, err := json.Marshal(project)
	if err != nil {
		return Result{}, err
	}
	var p model.Project
	if err = json.Unmarshal(raw, &p); err != nil {
		return Result{}, err
	}
	sort.Slice(p.Trees, func(i, j int) bool { return p.Trees[i].ID < p.Trees[j].ID })
	sort.Slice(p.Blackboard, func(i, j int) bool { return p.Blackboard[i].ID < p.Blackboard[j].ID })
	sort.Slice(p.Catalog, func(i, j int) bool { return p.Catalog[i].ID < p.Catalog[j].ID })
	for i := range p.Trees {
		p.Trees[i].Layout = nil
		sort.Slice(p.Trees[i].Nodes, func(a, b int) bool { return p.Trees[i].Nodes[a].ID < p.Trees[i].Nodes[b].ID })
	}
	for i := range p.Catalog {
		sort.Slice(p.Catalog[i].Params, func(a, b int) bool { return p.Catalog[i].Params[a].Name < p.Catalog[i].Params[b].Name })
		sort.Strings(p.Catalog[i].Events)
	}
	raw, _ = json.Marshal(p)
	sum := sha256.Sum256(raw)
	version := hex.EncodeToString(sum[:16])
	g := &generator{p: p, roots: map[string]int{}, defs: map[string]model.Definition{}, fields: map[string]int{}, context: p.Generation.ContextType}
	if p.Generation.ContextImport != "" {
		g.context = "ctxpkg." + strings.TrimPrefix(g.context, "*")
		if strings.HasPrefix(p.Generation.ContextType, "*") {
			g.context = "*" + g.context
		}
	}
	for _, d := range p.Catalog {
		g.defs[d.ID] = d
	}
	for i, f := range p.Blackboard {
		g.fields[f.ID] = i
	}
	trees := map[string]model.Tree{}
	indices := map[string]map[string]model.Node{}
	for _, t := range p.Trees {
		trees[t.ID] = t
		indices[t.ID] = map[string]model.Node{}
		for _, n := range t.Nodes {
			indices[t.ID][n.ID] = n
		}
	}
	var expand func(string, string, int) int
	expand = func(tree, id string, parent int) int {
		index := len(g.nodes)
		n := indices[tree][id]
		g.nodes = append(g.nodes, occurrence{node: n, tree: tree, parent: parent})
		var children []int
		if n.Type == "subtree" {
			childTree := trees[n.Tree]
			children = append(children, expand(childTree.ID, childTree.Root, index))
		} else {
			for _, child := range n.Children {
				children = append(children, expand(tree, child, index))
			}
		}
		g.nodes[index].children = children
		g.nodes[index].end = len(g.nodes)
		return index
	}
	for _, t := range p.Trees {
		g.roots[t.ID] = expand(t.ID, t.Root, -1)
	}
	g.line("// Code generated by behaviortree/codegen; DO NOT EDIT.")
	g.line("// 本文件使用原生 Go 分支与调用；业务函数请写在同包独立文件中。")
	g.line("package %s", p.Generation.Package)
	g.line("import (bt %q; \"time\"", "github.com/1xxz188/behaviortree")
	if p.Generation.ContextImport != "" {
		g.line("ctxpkg %q", p.Generation.ContextImport)
	}
	g.line(")")
	// 时长别名总是声明，保证没有计时节点的工程也不会产生未使用导入。
	g.line("type btDuration = time.Duration")
	for _, d := range p.Catalog {
		g.line("// %sParams 是业务函数的强类型参数。", d.GoName)
		g.line("type %sParams struct {", d.GoName)
		for _, param := range d.Params {
			g.line("// %s 由常量或黑板字段绑定提供。", param.Name)
			g.line("%s %s", param.Name, goType(param.Type))
		}
		g.line("}")
	}
	for i, f := range p.Blackboard {
		g.line("// Get%s 按编译后槽位读取黑板字段。", f.Name)
		g.line("func Get%s(f *bt.Frame[%s]) %s { return f.Board.%s(%d) }", f.Name, g.context, goType(f.Type), boardMethod(f.Type), i)
		g.line("// Set%s 在值变化时通知依赖条件。", f.Name)
		if f.Type == "enum" {
			// 允许值编译为静态分支，避免热路径遍历元数据或建立 map。
			g.line("func Set%s(f *bt.Frame[%s], value string) {switch value {", f.Name, g.context)
			choices := make([]string, len(f.Enum))
			for n, value := range f.Enum {
				choices[n] = strconv.Quote(value)
			}
			g.line("case %s:f.Board.SetEnum(%d,value)", strings.Join(choices, ","), i)
			g.line("default:panic(%q)}}", "invalid enum value for field "+f.ID)
		} else {
			g.line("func Set%s(f *bt.Frame[%s], value %s) { f.Board.Set%s(%d,value) }", f.Name, g.context, goType(f.Type), boardMethod(f.Type), i)
		}
	}
	g.line("// NewProgram 创建本版本共享的不可变程序，空版本名使用内容摘要。")
	g.line("func NewProgram(version string) *bt.Program[%s] {", g.context)
	g.line("if version == \"\" { version = %q }", version)
	g.line("return &bt.Program[%s]{Version:version, Roots:map[string]int{", g.context)
	for _, t := range p.Trees {
		g.line("%q:%d,", t.ID, g.roots[t.ID])
	}
	g.line("}, Nodes:[]bt.Node{")
	for _, n := range g.nodes {
		g.line("{ID:%q, TreeID:%q, Parent:%d, End:%d},", n.node.ID, n.tree, n.parent, n.end)
	}
	g.line("},Fields:[]bt.Field{")
	for _, f := range p.Blackboard {
		raw := f.Default
		if len(raw) == 0 {
			raw = model.Zero(f.Type, f.Enum)
		}
		g.line("{ID:%q,Name:%q,Type:bt.%s,Default:bt.Value{%s:%s},Enum:%s},", f.ID, f.Name, runtimeType(f.Type), valueMember(f.Type), literal(f.Type, raw), stringSlice(f.Enum))
	}
	g.line("},Dependencies:map[string][]int{")
	dependencies := map[string][]int{}
	for i, n := range g.nodes {
		if n.node.Type != "action" && n.node.Type != "condition" {
			continue
		}
		d := g.defs[n.node.Binding]
		seen := map[string]bool{}
		for _, event := range d.Events {
			seen["event:"+event] = true
		}
		for _, param := range n.node.Params {
			if param.Field != "" {
				seen["field:"+param.Field] = true
			}
		}
		for key := range seen {
			dependencies[key] = append(dependencies[key], i)
		}
	}
	keys := make([]string, 0, len(dependencies))
	for key := range dependencies {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		g.line("%q:%#v,", key, dependencies[key])
	}
	g.line("},Step:btStep,Abort:btAbort}")
	g.line("}")
	g.line("// btStep 通过整数槽位分派到编译后的节点函数。")
	g.line("func btStep(f *bt.Frame[%s], node int) bt.Status { switch node {", g.context)
	for i := range g.nodes {
		g.line("case %d:return btNode%d(f)", i, i)
	}
	g.line("};return bt.Failure }")
	g.line("// btAbort 仅清理当前动作；运行时负责活跃子树取消和状态失效。")
	g.line("func btAbort(f *bt.Frame[%s], node int) {switch node {", g.context)
	for i, n := range g.nodes {
		if n.node.Type == "action" {
			g.line("case %d: %s(f,%d,bt.Abort,%s)", i, g.defs[n.node.Binding].GoName, i, g.params(n.node))
		}
	}
	g.line("}}")
	for i := range g.nodes {
		g.emitNode(i)
	}
	source, err := format.Source(g.buf.Bytes())
	if err != nil {
		return Result{}, fmt.Errorf("格式化生成代码: %w", err)
	}
	fset := token.NewFileSet()
	parsed, err := parser.ParseFile(fset, "tree.gen.go", source, 0)
	if err != nil {
		return Result{}, err
	}
	lines := map[string]int{}
	for _, d := range parsed.Decls {
		if f, ok := d.(*ast.FuncDecl); ok {
			lines[f.Name.Name] = fset.Position(f.Pos()).Line
		}
	}
	mapping := make([]SourceLocation, len(g.nodes))
	for i, n := range g.nodes {
		mapping[i] = SourceLocation{n.tree, n.node.ID, i, lines[fmt.Sprintf("btNode%d", i)]}
	}
	return Result{Source: source, SourceMap: mapping, Version: version}, nil
}

// line 追加一行可格式化的 Go 文本。
func (g *generator) line(format string, args ...any) { fmt.Fprintf(&g.buf, format+"\n", args...) }

// goType 将元数据值类型映射为静态 Go 类型。
func goType(t string) string {
	switch t {
	case "entity":
		return "uint64"
	case "enum":
		return "string"
	case "duration":
		return "btDuration"
	default:
		return t
	}
}

// boardMethod 选择直接槽位访问器。
func boardMethod(t string) string {
	switch t {
	case "bool":
		return "Bool"
	case "int64":
		return "Int"
	case "uint64":
		return "Uint"
	case "float64":
		return "Float"
	case "string":
		return "String"
	case "enum":
		return "Enum"
	case "entity":
		return "EntityID"
	default:
		return "Duration"
	}
}

// runtimeType 选择公共运行时的布局类型。
func runtimeType(t string) string {
	switch t {
	case "bool":
		return "BoolType"
	case "int64":
		return "IntType"
	case "uint64":
		return "UIntType"
	case "float64":
		return "FloatType"
	case "string":
		return "StringType"
	case "enum":
		return "EnumType"
	case "entity":
		return "EntityIDType"
	default:
		return "DurationType"
	}
}

// valueMember 选择公共 Value 的强类型成员。
func valueMember(t string) string {
	if t == "enum" {
		return "String"
	}
	return boardMethod(t)
}

// literal 将已校验常量转换为无注入可能的 Go 字面量。
func literal(t string, raw json.RawMessage) string {
	value, _ := model.Literal(t, raw, nil)
	switch v := value.(type) {
	case string:
		return strconv.Quote(v)
	case bool:
		return strconv.FormatBool(v)
	case int64:
		return strconv.FormatInt(v, 10)
	case uint64:
		return strconv.FormatUint(v, 10)
	case float64:
		return strconv.FormatFloat(v, 'g', -1, 64)
	default:
		panic("validated literal has unsupported type")
	}
}

// stringSlice 生成字符串常量切片。
func stringSlice(values []string) string {
	var out strings.Builder
	out.WriteString("[]string{")
	for _, v := range values {
		out.WriteString(strconv.Quote(v))
		out.WriteByte(',')
	}
	out.WriteByte('}')
	return out.String()
}

// params 构造直接传给业务函数的强类型参数，不经反射或动态字典。
func (g *generator) params(n model.Node) string {
	d := g.defs[n.Binding]
	var out strings.Builder
	out.WriteString(d.GoName + "Params{")
	for _, p := range d.Params {
		v, ok := n.Params[p.Name]
		out.WriteString(p.Name + ":")
		if ok && v.Field != "" {
			fmt.Fprintf(&out, "f.Board.%s(%d)", boardMethod(p.Type), g.fields[v.Field])
		} else {
			raw := v.Value
			if !ok {
				raw = p.Default
			}
			out.WriteString(literal(p.Type, raw))
		}
		out.WriteByte(',')
	}
	out.WriteByte('}')
	return out.String()
}

// emitNode 生成一个节点的真实分支、续跑游标和静态子函数调用。
func (g *generator) emitNode(i int) {
	n := g.nodes[i]
	g.line("// btNode%d 执行树 %q 中的节点 %q。", i, n.tree, n.node.ID)
	g.line("func btNode%d(f *bt.Frame[%s]) bt.Status {", i, g.context)
	g.line("if cached,run:=f.Enter(%d);!run{return cached}", i)
	g.line("s:=f.State(%d); _=s", i)
	exit := func(status string) { g.line("return f.Exit(%d,%s)", i, status) }
	switch n.node.Type {
	case "action":
		g.line("phase:=bt.Start;if s.Started{phase=bt.Resume};s.Started=true")
		exit(fmt.Sprintf("%s(f,%d,phase,%s)", g.defs[n.node.Binding].GoName, i, g.params(n.node)))
	case "condition":
		g.line("if %s(f,%d,%s) { return f.Exit(%d,bt.Success) }", g.defs[n.node.Binding].GoName, i, g.params(n.node), i)
		exit("bt.Failure")
	case "sequence", "selector":
		g.line("for { switch s.Cursor {")
		for j, child := range n.children {
			g.line("case %d: status:=btNode%d(f);if status==bt.Running{return f.Exit(%d,status)}", j, child, i)
			terminal := "bt.Failure"
			if n.node.Type == "selector" {
				terminal = "bt.Success"
			}
			g.line("if status==%s{s.Cursor=0;return f.Exit(%d,status)};s.Cursor++", terminal, i)
		}
		g.line("default:s.Cursor=0;")
		if n.node.Type == "sequence" {
			exit("bt.Success")
		} else {
			exit("bt.Failure")
		}
		g.line("}}")
	case "priority":
		// 只有当前分支被唤醒且其首守卫未变时，直接续跑，避免探测所有高优先守卫。
		g.line("if s.Count!=0&&f.State(s.Cursor).Status==bt.Running&&f.OnlyDirtyChild(%d,s.Cursor){guardDirty:=false;switch s.Cursor{", i)
		for _, child := range n.children {
			candidate := g.nodes[child]
			if candidate.node.Type == "sequence" && len(candidate.children) > 0 && g.nodes[candidate.children[0]].node.Type == "condition" {
				g.line("case %d:guardDirty=f.IsDirty(%d)", child, candidate.children[0])
			}
		}
		g.line("};if !guardDirty{status:=btStep(f,s.Cursor);if status!=bt.Failure{return f.Exit(%d,status)};s.Count=0}}", i)
		// 先仅求值 guard，确定候选后再取消旧分支，避免新旧动作交叠。
		for j, child := range n.children {
			candidate := g.nodes[child]
			guard := -1
			if candidate.node.Type == "sequence" && len(candidate.children) > 0 && g.nodes[candidate.children[0]].node.Type == "condition" {
				guard = candidate.children[0]
			}
			if guard >= 0 {
				g.line("previousGuard%d:=f.State(%d).Status;guard%d:=btNode%d(f);if guard%d==bt.Running{return f.Exit(%d,bt.Running)}", j, guard, j, guard, j, i)
				// 失败候选只在守卫从真变假后重新待命，不因低优先动作事件反复重试。
				g.line("if previousGuard%d==bt.Success&&guard%d==bt.Failure&&f.State(%d).Status==bt.Failure{f.Reset(%d)}", j, j, child, child)
				g.line("if guard%d==bt.Success {", j)
			} else {
				g.line("{")
			}
			g.line("if s.Count!=0&&s.Cursor!=%d {f.Abort(s.Cursor,\"priority preempted\")};s.Count=1;s.Cursor=%d", child, child)
			g.line("status:=btNode%d(f);if status!=bt.Failure {return f.Exit(%d,status)};s.Count=0", child, i)
			g.line("}")
		}
		g.line("if s.Count!=0 {f.Abort(s.Cursor,\"priority guard failed\")};s.Count=0")
		exit("bt.Failure")
	case "parallel":
		// 首次按显式顺序启动全部分支；预算不足时保留尚未启动的位置。
		g.line("for s.Cursor<%d {var child int;var status bt.Status;switch s.Cursor {", len(n.children))
		for j, child := range n.children {
			g.line("case %d:child=%d;status=btNode%d(f)", j, child, child)
		}
		g.line("};if status==bt.Running&&f.State(child).Status==bt.Invalid{return f.Exit(%d,bt.Running)}", i)
		g.line("if status==bt.Failure{f.AbortChildren(%d,\"parallel failed\");return f.Exit(%d,bt.Failure)};if status==bt.Success{s.Count++};s.Cursor++}", i, i)
		// 后续仅取实际收到通知的直接分支，完成分支在本轮保持终态。
		g.line("for child:=f.PopDirtyChild(%d);child>=0;child=f.PopDirtyChild(%d){if f.State(child).Status==bt.Success{continue};var status bt.Status;switch child{", i, i)
		for _, child := range n.children {
			g.line("case %d:status=btNode%d(f)", child, child)
		}
		g.line("};if status==bt.Failure{f.AbortChildren(%d,\"parallel failed\");return f.Exit(%d,bt.Failure)};if status==bt.Success{s.Count++}}", i, i)
		g.line("if s.Count==%d{return f.Exit(%d,bt.Success)}", len(n.children), i)
		exit("bt.Running")
	case "repeat", "retry":
		child := n.children[0]
		g.line("for s.Count<%d {status:=btNode%d(f);if status==bt.Running{return f.Exit(%d,status)}", n.node.Count, child, i)
		terminal := "bt.Failure"
		finish := "bt.Success"
		if n.node.Type == "retry" {
			terminal, finish = "bt.Success", "bt.Failure"
		}
		g.line("if status==%s{return f.Exit(%d,status)};s.Count++;if s.Count<%d{f.Reset(%d)}", terminal, i, n.node.Count, child)
		g.line("}")
		exit(finish)
	case "wait":
		if n.node.DurationMS == 0 {
			exit("bt.Success")
		} else {
			g.line("if s.Ready {f.Consume(%d);return f.Exit(%d,bt.Success)}", i, i)
			g.line("if !s.Started{s.Started=true;f.After(%d,time.Duration(%d)*time.Millisecond)}", i, n.node.DurationMS)
			exit("bt.Running")
		}
	case "timeout":
		child := n.children[0]
		if n.node.DurationMS == 0 {
			g.line("f.Abort(%d,\"timeout\")", child)
			exit("bt.Failure")
		} else {
			g.line("if s.Ready {f.Consume(%d);f.Abort(%d,\"timeout\");return f.Exit(%d,bt.Failure)}", i, child, i)
			g.line("if !s.Started{s.Started=true;f.After(%d,time.Duration(%d)*time.Millisecond)}", i, n.node.DurationMS)
			exit(fmt.Sprintf("btNode%d(f)", child))
		}
	case "subtree":
		exit(fmt.Sprintf("btNode%d(f)", n.children[0]))
	case "inverter", "succeed", "fail":
		g.line("status:=btNode%d(f);if status==bt.Running{return f.Exit(%d,status)}", n.children[0], i)
		switch n.node.Type {
		case "inverter":
			g.line("if status==bt.Success{return f.Exit(%d,bt.Failure)}", i)
			exit("bt.Success")
		case "succeed":
			exit("bt.Success")
		case "fail":
			exit("bt.Failure")
		}
	}
	g.line("}")
}

// checkExpandedSize 先在无环树引用图上累计大小，超限前不创建任何展开节点。
func checkExpandedSize(p model.Project) error {
	trees := make(map[string]model.Tree, len(p.Trees))
	sizes := make(map[string]int, len(p.Trees))
	for _, t := range p.Trees {
		trees[t.ID] = t
	}
	var size func(string) int
	size = func(id string) int {
		if n, ok := sizes[id]; ok {
			return n
		}
		n := len(trees[id].Nodes)
		for _, node := range trees[id].Nodes {
			if node.Type == "subtree" {
				child := size(node.Tree)
				if n > MaxExpandedNodes-child {
					sizes[id] = MaxExpandedNodes + 1
					return MaxExpandedNodes + 1
				}
				n += child
			}
		}
		sizes[id] = n
		return n
	}
	total := 0
	for _, tree := range p.Trees {
		n := size(tree.ID)
		if n > MaxExpandedNodes-total {
			return &ValidationError{[]model.Diagnostic{{TreeID: tree.ID, Field: "trees", Message: fmt.Sprintf("子树展开超过 %d 个节点，请拆分工程或减少重复引用", MaxExpandedNodes)}}}
		}
		total += n
	}
	return nil
}
