package codegen

import (
	"go/parser"
	"go/token"
	"reflect"
	"strings"
	"testing"

	"github.com/1xxz188/behaviortree/model"
)

// TestPackagePathSharedByGeneratedFilesAndScaffold 验证嵌套路径、Windows 分隔符和骨架使用相同末级包名。
func TestPackagePathSharedByGeneratedFilesAndScaffold(t *testing.T) {
	for _, packagePath := range []string{"brawl", "ai/brawl", ` ai\brawl `} {
		t.Run(packagePath, func(t *testing.T) {
			project := model.Example()
			project.Generation.PackagePath = packagePath
			result, err := Generate(project)
			if err != nil {
				t.Fatal(err)
			}
			for _, file := range result.Files {
				if !strings.HasPrefix(string(file.Source), "// Code generated by behaviortree. DO NOT EDIT.\n") {
					t.Fatalf("文件缺少统一生成标记: %s", file.Name)
				}
				parsed, err := parser.ParseFile(token.NewFileSet(), file.Name, file.Source, parser.PackageClauseOnly)
				if err != nil || parsed.Name.Name != "brawl" {
					t.Fatalf("文件包名未从末级目录推导: %s, %v", file.Name, err)
				}
			}
			source, err := Scaffold(project)
			if err != nil {
				t.Fatal(err)
			}
			parsed, err := parser.ParseFile(token.NewFileSet(), "actions.go", source, parser.PackageClauseOnly)
			if err != nil || parsed.Name.Name != "brawl" {
				t.Fatalf("骨架包名未从末级目录推导: %v", err)
			}
			if project.Generation.PackagePath != packagePath {
				t.Fatal("生成修改了调用方包路径")
			}
		})
	}
}

// TestPackagePathNormalizationKeepsVersion 验证同一路径的不同分隔符不改变源码、映射和版本。
func TestPackagePathNormalizationKeepsVersion(t *testing.T) {
	project := model.Example()
	project.Generation.PackagePath = "ai/brawl"
	first, err := Generate(project)
	if err != nil {
		t.Fatal(err)
	}
	project.Generation.PackagePath = ` ai\brawl `
	second, err := Generate(project)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatal("路径规范化后生成结果不一致")
	}
	version, err := ProjectVersion(project)
	if err != nil || version != first.Version {
		t.Fatalf("预览版本与规范化生成版本不一致: %v", err)
	}
}

// TestInvalidPackagePathsRejectedBeforeGeneration 验证生成与骨架均在输出源码前拒绝逃逸路径和非法包名。
func TestInvalidPackagePathsRejectedBeforeGeneration(t *testing.T) {
	for _, packagePath := range []string{"", "../brawl", "ai/../brawl", "ai//brawl", "C:/brawl", "/tmp/brawl", "ai/bt-brawl", "ai/type"} {
		t.Run(packagePath, func(t *testing.T) {
			project := model.Example()
			project.Generation.PackagePath = packagePath
			if _, err := Generate(project); err == nil {
				t.Fatal("生成接受了非法包路径")
			}
			if _, err := Scaffold(project); err == nil {
				t.Fatal("骨架接受了非法包路径")
			}
		})
	}
}
