package editor

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/1xxz188/behaviortree/codegen"
)

// generatedSource 只接受本生成器的精确文件头，不误认其他工具生成的源码。
func generatedSource(source []byte) bool {
	return bytes.HasPrefix(source, []byte("// Code generated by behaviortree/codegen; DO NOT EDIT.\n")) || bytes.HasPrefix(source, []byte("// Code generated by behaviortree/codegen; DO NOT EDIT.\r\n"))
}

// artifactWrite 保存已经预检和暂存的单个待发布文件。
type artifactWrite struct {
	name string // 受限根内的目标路径。
	data []byte // 目标文件内容。
	temp string // 同目录临时文件路径。
}

// writeGenerated 先完整预检与暂存，再发布源码和清理废弃文件，最后提交映射清单。
func writeGenerated(root *os.Root, dir string, result codegen.Result) error {
	mapping := generatedMapping{Generator: "behaviortree/codegen", Version: result.Version, Locations: result.SourceMap, Files: make([]generatedFileMapping, len(result.Files))}
	total := 0
	for i, file := range result.Files {
		total += len(file.Source)
		if total > MaxGeneratedBytes {
			return errors.New("整批产物超过大小限制")
		}
		if !generatedSource(file.Source) {
			return errors.New("源码缺少本生成器标记")
		}
		mapping.Files[i] = generatedFileMapping{Name: file.Name, TreeID: file.TreeID, SHA256: sourceHash(file.Source)}
	}
	if err := validateManifest(mapping); err != nil {
		return err
	}
	raw, err := json.MarshalIndent(mapping, "", "  ")
	if err != nil {
		return err
	}
	if total+len(raw) > MaxGeneratedBytes {
		return errors.New("整批产物超过大小限制")
	}
	if err := root.MkdirAll(dir, 0755); err != nil {
		return err
	}
	manifestName := filepath.Join(dir, "tree_gen.map.json")
	budget := int64(MaxGeneratedBytes)
	oldRaw, err := readArtifact(root, manifestName, &budget)
	var old generatedMapping
	if err == nil {
		if err = json.Unmarshal(oldRaw, &old); err != nil {
			return fmt.Errorf("拒绝覆盖无效清单: %w", err)
		}
		if err = validateManifest(old); err != nil {
			return err
		}
	} else if !errors.Is(err, fs.ErrNotExist) {
		return err
	}

	// 合并目标和清理清单后只读取每个已有文件一次，未变化文件保留修改时间。
	targets := make(map[string][]byte, len(result.Files))
	names := make([]string, 0, len(result.Files)+len(old.Files))
	seen := make(map[string]bool, cap(names))
	for _, file := range result.Files {
		targets[file.Name] = file.Source
		names = append(names, file.Name)
		seen[artifactNameKey(file.Name)] = true
	}
	for _, file := range old.Files {
		if !seen[artifactNameKey(file.Name)] {
			names = append(names, file.Name)
			seen[artifactNameKey(file.Name)] = true
		}
	}
	writes := make([]artifactWrite, 0, len(result.Files)+1)
	remove := make([]string, 0)
	for _, name := range names {
		path := filepath.Join(dir, name)
		previous, err := readArtifact(root, path, &budget)
		exists := err == nil
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		if exists && !generatedSource(previous) {
			return fmt.Errorf("拒绝覆盖或清理手写文件 %s", path)
		}
		if next, ok := targets[name]; ok {
			if !exists || !bytes.Equal(previous, next) {
				writes = append(writes, artifactWrite{name: path, data: next})
			}
		} else if exists {
			remove = append(remove, path)
		}
	}
	if !bytes.Equal(oldRaw, raw) {
		writes = append(writes, artifactWrite{name: manifestName, data: raw})
	}
	defer func() {
		for _, write := range writes {
			if write.temp != "" {
				_ = root.Remove(write.temp)
			}
		}
	}()
	for i := range writes {
		temp, err := stageArtifact(root, writes[i].name, writes[i].data)
		if err != nil {
			return err
		}
		writes[i].temp = temp
	}
	// 清单是批次提交点；中断时旧清单与已发布文件的摘要不一致，重读会明确拒绝。
	for _, write := range writes {
		if write.name != manifestName {
			if err := root.Rename(write.temp, write.name); err != nil {
				return err
			}
		}
	}
	for _, name := range remove {
		if err := root.Remove(name); err != nil {
			return err
		}
	}
	for _, write := range writes {
		if write.name == manifestName {
			return root.Rename(write.temp, write.name)
		}
	}
	return nil
}

// artifactNameKey 在 Windows 合并同一路径的大小写别名，避免改号后将刚发布的文件当作旧文件删除。
func artifactNameKey(name string) string {
	if runtime.GOOS == "windows" {
		return strings.ToLower(name)
	}
	return name
}

// stageArtifact 同目录写入并同步临时文件，所有暂存完成前不修改正式产物。
func stageArtifact(root *os.Root, name string, data []byte) (string, error) {
	var nonce [8]byte
	if _, err := rand.Read(nonce[:]); err != nil {
		return "", err
	}
	temp := filepath.Join(filepath.Dir(name), ".bt-"+hex.EncodeToString(nonce[:])+".tmp")
	f, err := root.OpenFile(temp, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0644)
	if err != nil {
		return "", err
	}
	if _, err = f.Write(data); err == nil {
		err = f.Sync()
	}
	if closeErr := f.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		_ = root.Remove(temp)
		return "", err
	}
	return temp, nil
}
